# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='order_date',
            field=models.DateField(verbose_name='Date of allocation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_end_date',
            field=models.DateField(verbose_name='Actual end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_start_date',
            field=models.DateField(verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='Tentative end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Tentative start date'),
        ),
        migrations.AlterField(
            model_name='workassigned',
            name='actual_finish_date',
            field=models.DateField(verbose_name='Actual date of completion'),
        ),
        migrations.AlterField(
            model_name='workassigned',
            name='actual_start_date',
            field=models.DateField(verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='workassigned',
            name='finish_date',
            field=models.DateField(verbose_name='Expected date of completion'),
        ),
        migrations.AlterField(
            model_name='workassigned',
            name='start_date',
            field=models.DateField(verbose_name='Expected start date'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_date',
            field=models.DateField(verbose_name='Date of order'),
        ),
        migrations.AlterField(
            model_name='workprogress',
            name='new_deadline',
            field=models.DateField(verbose_name='Promised date of completion'),
        ),
    ]
