# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_auto_20160923_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual end date'),
        ),
    ]
