# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_auto_20160923_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tentative end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tentative start date'),
        ),
        migrations.AlterField(
            model_name='workassigned',
            name='actual_finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual date of completion'),
        ),
        migrations.AlterField(
            model_name='workassigned',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='workassigned',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected date of completion'),
        ),
    ]
