# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_auto_20160923_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='long_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Firm Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ONHOLD', 'On Hold'), ('CANCELED', 'canceled'), ('CLOSED', 'Closed'), ('NOT_STARTED', 'Not started')], max_length=50, verbose_name='Completion status'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ONHOLD', 'On Hold'), ('CANCELED', 'canceled'), ('CLOSED', 'Closed'), ('NOT_STARTED', 'Not started')], max_length=50, verbose_name='Completion status'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='ref_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.WorkOrder'),
        ),
    ]
