# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_auto_20160923_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='ref_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.Allocation'),
        ),
    ]
