# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_auto_20160924_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkProgress',
            new_name='WorkSchedule',
        ),
    ]
