# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_auto_20160924_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignFieldOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.Package')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer', models.CharField(max_length=100, verbose_name='Officer')),
                ('mobile', models.CharField(max_length=30, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inspections/%Y/%m/%d/')),
                ('desc_text', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspecting_on', models.DateField(verbose_name='Inspecting on')),
                ('inspected_on', models.DateField(verbose_name='Inspected on')),
                ('remark', models.TextField(verbose_name='Remark')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.AssignFieldOfficer')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionRosterDelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_inspection_date', models.DateField(verbose_name='New Schedule')),
                ('conversation', models.TextField(verbose_name='Cause text')),
                ('inspection_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.InspectionRoster')),
            ],
        ),
        migrations.CreateModel(
            name='LTWorkExecutionHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_dtr', models.IntegerField(verbose_name='No. of DTRs')),
                ('no_of_poles_2erect', models.IntegerField(verbose_name='No. of poles to be erected')),
                ('length_of_cable_2string', models.IntegerField(verbose_name='Length of Cable to be string')),
                ('no_of_poles_2dismantle', models.IntegerField(verbose_name='No. of poles to be dismantled')),
                ('length_of_cable_2dismantle', models.IntegerField(verbose_name='Length of Cable to be dismantled')),
                ('work_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.WorkAssigned')),
            ],
        ),
        migrations.CreateModel(
            name='LTWorkExecutionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_poles_erected', models.IntegerField(verbose_name='No. of poles erected')),
                ('length_of_cable_strung', models.IntegerField(verbose_name='Length of Cable strung')),
                ('no_of_poles_dismantled', models.IntegerField(verbose_name='No. of poles dismantled')),
                ('length_of_cable_dismantled', models.IntegerField(verbose_name='Length of Cable dismantled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('firm_comment', models.TextField(verbose_name='Comment by firm')),
                ('supervisor_remark', models.TextField(verbose_name='Comment by supervisor')),
                ('internal_remark', models.TextField(verbose_name='Comment by PMU')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.LTWorkExecutionHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_as_on', models.DateField(unique=True, verbose_name='Report as on')),
                ('desc_text', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='ltworkexecutionitem',
            name='report_due_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.ReportRoster', to_field='report_as_on'),
        ),
        migrations.AddField(
            model_name='inspectionreportfile',
            name='inspection_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.InspectionRoster'),
        ),
        migrations.AddField(
            model_name='assignfieldofficer',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.FieldOfficer'),
        ),
    ]
