# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0011_auto_20160924_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltworkexecutionheader',
            name='length_of_cable_2dismantle',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Length of Cable to be dismantled'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionheader',
            name='length_of_cable_2string',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Length of Cable to be string'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionitem',
            name='firm_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment by firm'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionitem',
            name='internal_remark',
            field=models.TextField(blank=True, null=True, verbose_name='Comment by PMU'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionitem',
            name='length_of_cable_dismantled',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Length of Cable dismantled'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionitem',
            name='length_of_cable_strung',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Length of Cable strung'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionitem',
            name='supervisor_remark',
            field=models.TextField(blank=True, null=True, verbose_name='Comment by supervisor'),
        ),
    ]
