# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0012_auto_20160924_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField()),
                ('task', models.CharField(max_length=100)),
            ],
        ),
    ]
