# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0014_ltworkexecutionitem_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10, verbose_name='Field type ✋')),
                ('subtext', models.CharField(max_length=100, verbose_name='Subtext')),
                ('default', models.BooleanField(verbose_name='Default')),
            ],
        ),
        migrations.AlterField(
            model_name='ltworkexecutionheader',
            name='length_of_cable_2string',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Length of Cable to be strung'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionitem',
            name='firm_comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comment by firm'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionitem',
            name='internal_remark',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comment by PMU'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionitem',
            name='supervisor_remark',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comment by supervisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='reportroster',
            name='desc_text',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reportroster',
            name='report_as_on',
            field=models.DateField(unique=True, verbose_name='📅 Report as on'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Sub-division Name'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order',
            field=models.CharField(max_length=50, unique=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='subtext',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.SubText'),
        ),
    ]
