# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0015_auto_20160925_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='subtext',
        ),
    ]
