# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0017_auto_20160925_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassigned',
            name='ref_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workorders.WorkOrder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation',
            name='order',
            field=models.CharField(max_length=50, unique=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='division',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Division Name'),
        ),
        migrations.AlterField(
            model_name='fieldofficer',
            name='officer',
            field=models.CharField(max_length=100, unique=True, verbose_name='👤Officer'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='short_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Firm Name'),
        ),
        migrations.AlterField(
            model_name='inspectionroster',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='inspectionrosterdelta',
            name='conversation',
            field=models.CharField(max_length=200, verbose_name='Cause text'),
        ),
        migrations.AlterField(
            model_name='package',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Sub-division Name'),
        ),
        migrations.AlterField(
            model_name='workassigned',
            name='ref_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.Allocation'),
        ),
    ]
