# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0018_auto_20160927_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of DTR')),
                ('about', models.CharField(blank=True, max_length=100, null=True, verbose_name='About the DTR')),
                ('areas_covered', models.TextField(blank=True, null=True, verbose_name='Areas covered')),
                ('kva', models.IntegerField(blank=True, null=True, verbose_name='Rating in KVA')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NOTOK', 'Not OK')], max_length=50, verbose_name='Status')),
                ('status_txt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status text')),
                ('no_poles', models.IntegerField(blank=True, null=True, verbose_name='Total number of poles')),
                ('length_cable', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Coverage in length (KM)')),
                ('date_of_manu', models.DateField(blank=True, null=True, verbose_name='Date of manufacture')),
                ('date_of_comm', models.DateField(blank=True, null=True, verbose_name='Date of commission')),
                ('model_number', models.CharField(max_length=100, unique=True, verbose_name='Model number')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer')),
                ('vendor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/DTR/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of DTR')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NOTOK', 'Not OK')], max_length=50, verbose_name='Status')),
                ('status_txt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status text')),
                ('about', models.TextField(verbose_name='About the feeder')),
            ],
        ),
        migrations.RemoveField(
            model_name='ltworkexecutionheader',
            name='no_of_dtr',
        ),
        migrations.AddField(
            model_name='allocation',
            name='reqd_type',
            field=models.CharField(choices=[('INITIAL', 'Initial allocation'), ('ADDNL', 'Additional')], default='INITIAL', max_length=50, verbose_name='Requirement type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ltworkexecutionheader',
            name='length_of_cable_2dismantle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Length of Cable to be dismantled'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionheader',
            name='length_of_cable_2string',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Length of Cable to be strung'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionheader',
            name='no_of_poles_2dismantle',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of poles to be dismantled'),
        ),
        migrations.AlterField(
            model_name='ltworkexecutionheader',
            name='no_of_poles_2erect',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of poles to be erected'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='work_orders/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='dtr',
            name='feeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.Feeder'),
        ),
        migrations.AddField(
            model_name='dtr',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.Package'),
        ),
        migrations.AddField(
            model_name='ltworkexecutionheader',
            name='dtr',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='workorders.DTR'),
            preserve_default=False,
        ),
    ]
