# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0019_auto_20160927_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltworkexecutionheader',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.Package'),
        ),
    ]
